name: e350_notebook
channels:
  - conda-forge
dependencies:
  - mamba
  - notebook
  - jupyterhub
  - jupyterlab
  - bokeh
  - conda-lock
  - ghp-import
  - git
  - jupytext
  - jupyter-resource-usage
  - matplotlib
  - numpy
  - nbgitpuller
  - pandas
  - pip
  - pillow
  - python<3.10
  - discretize
  - empymod
  - ipywidgets
  - mkl
  - pymatsolver
  - qtconsole
  - qtpy
  - scipy
  - scikit-learn
  - SimPEG
# conda-lock --kind explicit --file environment.yml -p linux-64
